#!/bin/bash
# -*- coding: utf-8 -*-
# Nobel订单管理系统 - 快速部署向导

echo "=========================================="
echo "🚀 Nobel订单管理系统 - 部署向导"
echo "=========================================="
echo ""

echo "请选择部署方案："
echo ""
echo "1. Streamlit Cloud（推荐，免费，3分钟部署）"
echo "2. 云服务器（稳定，50-100元/月）"
echo "3. 隧道服务（临时，免费）"
echo "4. 查看详细对比"
echo ""
echo "=========================================="
echo ""
read -p "请输入选项 (1-4): " choice

case $choice in
    1)
        echo ""
        echo "=========================================="
        echo "📝 Streamlit Cloud 部署步骤"
        echo "=========================================="
        echo ""
        echo "步骤 1: 准备 GitHub 仓库"
        echo "----------------------------------------"
        echo "cd /workspace/projects"
        echo "git init"
        echo "git add ."
        echo "git commit -m 'Initial commit'"
        echo ""
        echo "步骤 2: 推送到 GitHub"
        echo "----------------------------------------"
        echo "1. 访问 https://github.com/new 创建仓库"
        echo "2. 仓库名：nobel-order-system"
        echo "3. 执行以下命令："
        echo ""
        echo "git remote add origin https://github.com/你的用户名/nobel-order-system.git"
        echo "git push -u origin main"
        echo ""
        echo "步骤 3: 部署到 Streamlit Cloud"
        echo "----------------------------------------"
        echo "1. 访问 https://share.streamlit.io/"
        echo "2. 登录 GitHub 账号"
        echo "3. 点击 'New app'"
        echo "4. 选择仓库：nobel-order-system"
        echo "5. 选择分支：main"
        echo "6. 主文件路径：src/app_server.py"
        echo "7. 点击 'Deploy'"
        echo ""
        echo "步骤 4: 配置环境变量"
        echo "----------------------------------------"
        echo "在部署页面的 Secrets 部分添加："
        echo ""
        echo "[supabase]"
        echo "project_url = \"你的 Supabase Project URL\""
        echo "anon_key = \"你的 Supabase anon key\""
        echo "service_role_key = \"你的 Supabase service role key\""
        echo ""
        echo "步骤 5: 等待部署完成"
        echo "----------------------------------------"
        echo "等待 1-3 分钟，你会看到："
        echo ""
        echo "✅ Your app is running!"
        echo "🌐 URL: https://nobel-order-system.streamlit.app"
        echo ""
        echo "📖 详细文档：docs/DEPLOY_STREAMLIT_CLOUD.md"
        echo ""
        ;;

    2)
        echo ""
        echo "=========================================="
        echo "📝 云服务器部署步骤"
        echo "=========================================="
        echo ""
        echo "步骤 1: 购买云服务器"
        echo "----------------------------------------"
        echo "推荐配置："
        echo "  - CPU: 2核"
        echo "  - 内存: 4GB"
        echo "  - 带宽: 5Mbps"
        echo "  - 系统: Ubuntu 22.04"
        echo "  - 费用: 50-100元/月"
        echo ""
        echo "推荐服务商："
        echo "  - 阿里云: https://www.aliyun.com/product/ecs"
        echo "  - 腾讯云: https://cloud.tencent.com/product/cvm"
        echo "  - 华为云: https://www.huaweicloud.com/product/cvm"
        echo ""
        echo "步骤 2: 连接服务器"
        echo "----------------------------------------"
        echo "ssh root@你的公网IP"
        echo ""
        echo "步骤 3: 上传部署脚本"
        echo "----------------------------------------"
        echo "在本地电脑执行："
        echo ""
        echo "scp scripts/deploy_to_server.sh root@你的公网IP:/root/"
        echo "scp scripts/setup_ssl.sh root@你的公网IP:/root/"
        echo ""
        echo "步骤 4: 运行部署脚本"
        echo "----------------------------------------"
        echo "在服务器上执行："
        echo ""
        echo "bash /root/deploy_to_server.sh"
        echo ""
        echo "步骤 5: 上传代码"
        echo "----------------------------------------"
        echo "方式1：使用 Git"
        echo "git clone https://github.com/你的用户名/nobel-order-system.git /opt/nobel-order-system"
        echo ""
        echo "方式2：手动上传"
        echo "scp -r /workspace/projects/* root@你的公网IP:/opt/nobel-order-system/"
        echo ""
        echo "步骤 6: 重启服务"
        echo "----------------------------------------"
        echo "supervisorctl restart nobel-order-system"
        echo ""
        echo "步骤 7: （可选）配置 HTTPS"
        echo "----------------------------------------"
        echo "bash /root/setup_ssl.sh"
        echo ""
        echo "📖 详细文档：docs/DEPLOY_CLOUD_SERVER.md"
        echo ""
        ;;

    3)
        echo ""
        echo "=========================================="
        echo "📝 隧道服务方案"
        echo "=========================================="
        echo ""
        echo "方案1: Serveo（最简单）"
        echo "----------------------------------------"
        echo "在您的本地电脑终端执行："
        echo ""
        echo "ssh -R 80:9.128.127.13:8501 serveo.net"
        echo ""
        echo "等待显示外网地址（如 https://abc123.serveo.net）"
        echo "分享这个地址给同事！"
        echo ""
        echo "=========================================="
        echo ""
        echo "方案2: Localtunnel（推荐）"
        echo "----------------------------------------"
        echo "1. 安装工具（只需一次）："
        echo "npm install -g localtunnel"
        echo ""
        echo "2. 启动隧道："
        echo "lt --port 8501 --subdomain nobel-orders"
        echo ""
        echo "3. 复制显示的URL（如 https://nobel-orders.loca.lt）"
        echo ""
        echo "=========================================="
        echo ""
        echo "方案3: Cloudflare Tunnel（最稳定）"
        echo "----------------------------------------"
        echo "1. 访问注册 Cloudflare（免费）："
        echo "https://dash.cloudflare.com/sign-up"
        echo ""
        echo "2. 下载 cloudflared："
        echo "https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/"
        echo ""
        echo "3. 运行隧道："
        echo "cloudflared tunnel --url http://9.128.127.13:8501"
        echo ""
        echo "💡 查看更多方案：python scripts/show_tunnel_solutions.py"
        echo ""
        ;;

    4)
        echo ""
        echo "=========================================="
        echo "📊 部署方案对比"
        echo "=========================================="
        echo ""
        echo "方案                  | 难度 | 费用       | 时间     | 稳定性 | 推荐度"
        echo "---------------------|------|-----------|----------|--------|--------"
        echo "Streamlit Cloud      | ⭐   | 免费      | 3分钟    | ⭐⭐⭐⭐ | ⭐⭐⭐⭐⭐"
        echo "云服务器             | ⭐⭐⭐ | 50-100元/月| 10-30分钟| ⭐⭐⭐⭐⭐| ⭐⭐⭐⭐"
        echo "隧道服务             | ⭐⭐  | 免费      | 5分钟    | ⭐⭐    | ⭐⭐"
        echo ""
        echo "=========================================="
        echo ""
        echo "🎯 推荐方案"
        echo "=========================================="
        echo ""
        echo "✅ 小团队（<10人）  → Streamlit Cloud（免费、简单）"
        echo "✅ 中大型团队（>10人）→ 云服务器（性能好、专业）"
        echo "✅ 临时测试        → 隧道服务（快速、免费）"
        echo ""
        echo "💡 最推荐：Streamlit Cloud"
        echo "   - 完全免费"
        echo "   - 3分钟部署"
        echo "   - 固定URL"
        echo "   - 自动HTTPS"
        echo "   - 全球访问"
        echo "   - 零维护"
        echo ""
        echo "📖 详细文档：docs/DEPLOYMENT_GUIDE.md"
        echo ""
        ;;

    *)
        echo "无效选项"
        exit 1
        ;;
esac

echo ""
echo "=========================================="
echo "📚 相关文档"
echo "=========================================="
echo ""
echo "1. 部署指南总结：docs/DEPLOYMENT_GUIDE.md"
echo "2. Streamlit Cloud部署：docs/DEPLOY_STREAMLIT_CLOUD.md"
echo "3. 云服务器部署：docs/DEPLOY_CLOUD_SERVER.md"
echo "4. 快速使用教程：docs/QUICK_START_TUTORIAL.md"
echo ""
echo "=========================================="
