#!/bin/bash
# -*- coding: utf-8 -*-
# 快速生成外网访问地址

echo "=========================================="
echo "🌍 Nobel订单管理系统 - 外网访问设置"
echo "=========================================="
echo ""

echo "📌 当前服务地址："
echo "   - 服务器地址: 9.128.127.13:8501"
echo "   - 状态: 运行中 ✅"
echo ""

echo "=========================================="
echo "🚀 选择外网访问方案"
echo "=========================================="
echo ""
echo "方案1: Serveo 隧道（最简单，无需安装）"
echo "------------------------------------------"
echo "在您的本地电脑终端执行："
echo ""
echo "   ssh -R 80:9.128.127.13:8501 serveo.net"
echo ""
echo "等待显示外网地址（如 https://abc123.serveo.net）"
echo ""
echo "=========================================="
echo ""
echo "方案2: Localtunnel（推荐，稳定）"
echo "------------------------------------------"
echo "1. 安装工具（只需一次）："
echo "   npm install -g localtunnel"
echo ""
echo "2. 启动隧道："
echo "   lt --port 8501 --subdomain nobel-orders"
echo ""
echo "3. 复制显示的URL（如 https://nobel-orders.loca.lt）"
echo ""
echo "=========================================="
echo ""
echo "方案3: Cloudflare Tunnel（最稳定）"
echo "------------------------------------------"
echo "1. 访问注册 Cloudflare（免费）："
echo "   https://dash.cloudflare.com/sign-up"
echo ""
echo "2. 下载 cloudflared："
echo "   https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/"
echo ""
echo "3. 运行隧道："
echo "   cloudflared tunnel --url http://9.128.127.13:8501"
echo ""
echo "=========================================="
echo ""
echo "💡 快速开始推荐："
echo ""
echo "   在您的本地电脑打开终端，输入："
echo ""
echo "   ssh -R 80:9.128.127.13:8501 serveo.net"
echo ""
echo "   然后分享显示的外网地址给同事！"
echo ""
echo "=========================================="
